header:
  version: 14
  includes:
    - kas/include/configs/dev/common.yml
    - kas/include/configs/dev/rm_work.yml
    - kas/include/layers/yfs-layer.yml

local_conf_header:
  ditro-options: |
    NO_RECOMMENDATION = "1"
    
distro: yfs